import streamlit
streamlit.title('Our diet menu')
streamlit.header('Dinner')
streamlit.text('Monday: Puttu')
streamlit.text('Tuesday: Solakarudhu Salad')
streamlit.text('Wednesday: Karuppu Arisi Kanji')
streamlit.text('Thursday: Sundal')
streamlit.text('Friday: Aval Sundal')
streamlit.text('Saturday: Fruit Salad after evening snacks')
streamlit.text('Sunday: Anything based on mood')
